### ISSUE TITLE
Not available on pypi

### ISSUE THREAD

**Issue by unixfox** [WedjaaOpen/taiga-contrib-gitlab-auth#1]
When I run the command: `pip install taiga-contrib-gitlab-auth`
Pip return me that package doesn't exist:

```
Downloading/unpacking taiga-contrib-gitlab-auth
  Could not find any downloads that satisfy the requirement taiga-contrib-gitlab-auth
Cleaning up...
No distributions at all found for taiga-contrib-gitlab-auth
Storing debug log for failure in /home/taiga/.pip/pip.log
```

Can you add the package on [Pypi](https://pypi.python.org)?

**Comment by Wedjaa** [comment]
Plan is to publish it in Pypi once I get around completing the tests.

**Comment by Wedjaa** [comment]
The plugin is now published on PyPi!
