### ISSUE TITLE
Callback url ?

### ISSUE THREAD

**Issue by unixfox** [WedjaaOpen/taiga-contrib-gitlab-auth#2]
Hi !

I've setup taiga gitlab auth but I don't know what I've to fill in the callback url on my gitlab application?

![](https://i.unixfox.eu/00-01-33-2016.png)

**Comment by unixfox** [comment]
Okay I found the url: https://taiga.exemple.com/login

**Comment by ghost** [comment]
This should be noted in documentation

**Comment by Wedjaa** [comment]
Added to the README!
